version: "3"
services:
  commissioner_exist_db:
    image: existdb/existdb:latest
    ports:
      - "8091:8080"
      - "8443:8443"
    networks:
      - xml-projekat
 
  authority_body_exist_db:
    image: existdb/existdb:latest
    ports:
      - "8092:8080"
      - "8444:8443"
    networks:
      - xml-projekat

  commissioner_fuseki_db:
    image: fuseki
    ports:
      - "3031:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=CommissionerDataset
    networks:
      - xml-projekat

  authority_body_fuseki_db:
    image: fuseki
    ports:
      - "3032:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=AuthorityBodyDataset
    networks:
      - xml-projekat


networks:
  xml-projekat: 