version: "3"
services:
  existdb:
    image: existdb/existdb:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - xml-projekat
 
  fusekidb:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    networks:
      - xml-projekat

networks:
  xml-projekat: 