
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.08 at 11:14:14 PM CET
//

@XmlSchema(
        namespace = "http://www.w3.org/ns/rdfa#",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI="http://www.w3.org/ns/rdfa#"),
                @javax.xml.bind.annotation.XmlNs(prefix = "ob", namespaceURI="http://www.ftn.uns.ac.rs/xml/tim11/obavestenje"),
                @javax.xml.bind.annotation.XmlNs(prefix = "xs", namespaceURI="http://www.w3.org/2001/XMLSchema#"),
                @javax.xml.bind.annotation.XmlNs(prefix="co", namespaceURI="http://www.ftn.uns.ac.rs/xml/tim11/common"),
                @javax.xml.bind.annotation.XmlNs(prefix="xsi", namespaceURI="http://www.w3.org/2001/XMLSchema-instance"),
                @javax.xml.bind.annotation.XmlNs(prefix="pred", namespaceURI="http://www.ftn.uns.ac.rs/xml/tim11/predicate/"),
        }
)
package rs.ac.uns.ftn.xml.tim11.authoritybodyservice.model.obavestenje;

import javax.xml.bind.annotation.XmlSchema;